-- USE restaurant;
-- INSERT INTO `customer` (`id`, `first_name`, `last_name`)
-- VALUES (NULL, 'Lucas', 'Maxwell'),
--        (NULL, 'Samantha', 'Carpenter'),
--        (NULL, 'Sonya', 'Sandoval'),
--        (NULL, 'Gordon', 'Franklin'),
--        (NULL, 'Russell', 'Benson');
--
-- INSERT INTO `restaurant` (`id`, `restaurant`, `cuisine`)
-- VALUES (NULL, 'dominos', 'pizza'),
--        (NULL, 'mcdonalds', 'burgers'),
--        (NULL, 'kfc', 'burgers');
--
-- INSERT INTO `menu` (`id`, `restaurant_id`, `item`, `price`, `available`)
-- VALUES (NULL, 1, 'hawaiian pizza', 9.99, true),
--        (NULL, 1, 'bbq pizza', 10.99, true),
--        (NULL, 1, 'margherita pizza', 5.99, false),
--        (NULL, 1, 'pepperoni pizza', 7.99, true),
--        (NULL, 2, 'cheese burger', 2.99, true),
--        (NULL, 2, 'beef burger', 1.99, true),
--        (NULL, 2, 'cheese burger', 1.99, false),
--        (NULL, 2, 'chicken nuggets', 3.99, true),
--        (NULL, 2, 'wrap', 3.49, true),
--        (NULL, 3, 'chicken pieces', 2.79, true),
--        (NULL, 3, 'chicken burger', 3.42, true),
--        (NULL, 3, 'wrap', 2.68, false);